### ISSUE TITLE
[Question] Rails migrations and Data migration possible conflicts

### ISSUE THREAD

**Issue by ghost** [pboling/seed_migration#62]
Hi! I have a question:
How can this gem work if migrations are not run alongside Rails migrations?
**note** *alongside meaning: all migrations (Rails ones and data ones) run together in chronological order looking at the timestamps*

Case scenario:
I have these Rails migrations
- create table dogs
- create table cats
- remove table dogs

And these data migrations
- add dog1
- add dog2
- add cat1
- remove dog1 and dog2

If I run `rake db:migrate` and then `rake seed:migrate`.
As soon as I run the second command, how can first data migration run at all?
dogs is no longer there.

**Comment by sameera207** [comment]
hey @ClaudioCarmeli , you have a valid point and I was able to replicate your issue too. 
[here is the repo](https://github.com/sameera207/seed_migration_test)

A quick solution I came up with was to override the `up` and `down` methods in [migrator.rb](https://github.com/harrystech/seed_migration/blob/master/lib/seed_migration/migrator.rb#L21) and rescue any errors. 

This of course used with caution since it sinks all the errors. However following are the  steps to implement this approach. 

- create a file in `config/initializers` (with any name)
- override the `up` and `down` methods

```
#config/initializers/seed_migration_error_handler.rb

module SeedMigration
  class Migrator
    original_up = instance_method(:up)
    original_down = instance_method(:down)

    define_method(:up) do
      begin
        original_up.bind(self).()
      rescue
      end
    end

    define_method(:down) do
      begin
        original_down.bind(self).()
      rescue
      end
    end
  end
end
```

**before**
![screen shot 2018-08-10 at 12 01 39 pm](https://user-images.githubusercontent.com/98407/43934977-313506e0-9c95-11e8-99ef-c3647dba16ee.png)


**after**
![screen shot 2018-08-10 at 12 02 19 pm](https://user-images.githubusercontent.com/98407/43935020-55fe691c-9c95-11e8-916a-2b3e58520ad5.png)



[ref for the awesome SO answer](https://stackoverflow.com/questions/4470108/when-monkey-patching-a-method-can-you-call-the-overridden-method-from-the-new-i)
 

@pjambet , if you think this can be a potential solution, I'm happy to do it in a proper way and maybe add a config option to decide if the user wants to skip the error or not, let me know your thoughts.

**Comment by pjambet** [comment]
Hi,

This is an interesting and is indeed a bit "dangerous" as you mentioned. I might have to think about it a bit more to decide if this is a use case that could be used as option to skip errors or not as you suggested.

I haven't used this gem in a while, so I forgot the actual workaround, but I believe that there is potentially a way to run the migrations in your example.

IIRC running `rake seed:migrate` (if successful) will end up refreshing the content of `db/seeds.rb`, even if no migrations were run.

So, you could technically "fake" the fact that some data migrations have been run by "manually" inserting them in the `data_migrations`, and that way `rake seed:migrate` would skip them.

Using this trick can be useful to get out of tricky situations, but I don't know if this is a common use case.

In your case I would have expected the flow to be:

- Run schema migration:  create table dogs
- Run data migration: add dog1
- Run data migration: add dog2 (`seeds.rb` now contains two entries for dogs)
- Run schema migration: create table cats
- Run schema migration remove table dogs
- Unregister the dog model in the config file
- Run `rake seed:migrate`, the `seeds.rb` file does not contain any entries for the dog model anymore
- Run data migration: add cat1

Let me know if I missed anything.

**Comment by sameera207** [comment]
@pjambet , Yes you are right, When I think about it more, I think this is not an everyday problem and cases like this is common to any data addition process. 

Even a db seed will fail if there is no table . (and Ideally it should too)

So, I agree with you on **not having** my above workaround as a feature on the gem itself. :)

**Comment by vhoyer** [comment]
What's the problem of running the seed:migrate and db:migrate chronologically alongside eachother?

**Comment by pboling** [comment]
If you remove the table later you likely need to edit your seeds.  DB migrations should be squashed down (see the [squasher](https://github.com/jalkoby/squasher) gem), because of the maintenance overhead of keeping the code in them "runnable", which often isn't even desirable.  DB seed migrations should follow the same concept, IMO.  If you have a use case that needs to create the records, and then remove the table, effectively interleaving seed_migrations with db migrations, that will need special attention, but I am not sure this gem would attempt to address it.

I know in my use case seed migrations use alpha-numeric sorting for order, while rails db migrations use a date stamp, so interleaving wouldn't work at all, and indeed the intent is for the seeds to run after the db migrations are complete.  I expect this use case is the most common.

If someone can make a PR that makes them run chronologically, if appropriately named with timestamps, as an option, I'd be happy to review it!

**Comment by pboling** [comment]
Closing this for now, but feel free to submit PRs, or other issues with ideas for enhancement.
